openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0
paths:
  /contacts:
    post:
      summary: Create a new contact
      description: Requires Bearer token for authentication
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: Contact created successfully
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
